apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-ms3-app
  labels:
    app: complete-ms3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : complete-ms3-app
  template:
    metadata:
      labels:
        app: complete-ms3-app
    spec:
      containers:
      - name: complete-ms3-app
        image: harbans2886/complete-ms3:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8084
        env:
        - name: ds-username
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: ds-password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password

---

kind: Service
apiVersion: v1
metadata:
  name:  complete-ms3-svc
spec:
  selector:
    app:  complete-ms3-app
  ports:
  - port:  80
    targetPort:  8084