server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MICROSER-1
          uri: lb://MICROSER-1
          predicates:
            - Path=/users/**
        - id: MICROSER-2
          uri: lb://MICROSER-2
          predicates:
            - Path=/clients/**
        - id: MICROSER-3
          uri: lb://MICROSER-3
          predicates:
            - Path=/employees/**
        - id: AUTH-SERVER
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/authenticate/**

eureka:
  instance:
    hostname: eureka-0
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
    base-path: /
