apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-ms1-app
  labels:
    app: complete-ms1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : complete-ms1-app
  template:
    metadata:
      labels:
        app: complete-ms1-app
    spec:
      containers:
      - name: complete-ms1-app
        image: harbans2886/complete-ms1:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8082

---

kind: Service
apiVersion: v1
metadata:
  name:  complete-ms1-svc
spec:
  selector:
    app:  complete-ms1-app
  ports:
  - port:  80
    targetPort:  8082